version: "3.9"

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  # web:
  #   build: ../demo3
  #   ports:
  #     - 4200:4200
  #   volumes:
  #     - ../demo3:/app/client
  # Node api service
  api:
    build: .
    ports:
      # local->container
      - 4000:8000
    environment:
      PORT: 8000
      MONGO_URI: mongodb://mongo_db:27017/
      DB_NAME: my_db
    volumes:
      - .:/app/api
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
